apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: abisheksmahesh2-poi-map-app-dev
  annotations:
    argocd/app-name: abisheksmahesh2-poi-map-app-dev
    backstage.io/kubernetes-id: abisheksmahesh2-poi-map-app
    backstage.io/kubernetes-namespace: abisheksmahesh2
    backstage.io/techdocs-ref: dir:.
    github.com/project-slug: rhdh-deploy/abisheksmahesh2-frontend
    janus-idp.io/tekton-enabled: 'true'
  tags:
    - typescript
    - angular
    - workshop
  links:
    - url: https://console-openshift-console.apps.a1jxqhzp.eastus2.aroapp.io/dev-pipelines/ns/abisheksmahesh2/
      title: Pipelines
      icon: web
    - url: https://console-openshift-console.apps.a1jxqhzp.eastus2.aroapp.io/k8s/ns/abisheksmahesh2/deployments/abisheksmahesh2-poi-map-app
      title: Deployment
      icon: web
    - url: https://devspaces.apps.a1jxqhzp.eastus2.aroapp.io/#https://github.com/rhdh-deploy/abisheksmahesh2-frontend?che-editor=che-incubator/che-code/latest&devfilePath=.devfile-vscode.yaml
      title: OpenShift Dev Spaces (VS Code)
      icon: web
    - url: http://abisheksmahesh2-poi-map-app-abisheksmahesh2.apps.a1jxqhzp.eastus2.aroapp.io
      title: Map
      icon: web
spec:
  type: service
  lifecycle: production
  owner: "user:default/abisheksmahesh"
  system: workshop-system-abisheksmahesh2
  consumesApis:
    - gateway-api-abisheksmahesh2
---
apiVersion: backstage.io/v1alpha1
kind: System
metadata:
  name: workshop-system-abisheksmahesh2
  tags:
    - backstage
    - janus-idp
    - openshift
    - workshop
    - rh-summit
spec:
  owner: "user:default/abisheksmahesh"
